name: admet_env
channels:
  - conda-forge
dependencies:
  - flask
  - flask-cors
  - rdkit
  - scikit-learn
  - joblib
  - xgboost
  - pandas
  - numpy
  - reportlab
  - matplotlib
  - seaborn
  - pip
  - pip:
      - gunicorn
